// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: protos/sandbox.proto

package sandbox

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Languages int32

const (
	Languages_JAVASCRIPT Languages = 0
	Languages_TYPESCRIPT Languages = 1
	Languages_GOLANG     Languages = 2
)

// Enum value maps for Languages.
var (
	Languages_name = map[int32]string{
		0: "JAVASCRIPT",
		1: "TYPESCRIPT",
		2: "GOLANG",
	}
	Languages_value = map[string]int32{
		"JAVASCRIPT": 0,
		"TYPESCRIPT": 1,
		"GOLANG":     2,
	}
)

func (x Languages) Enum() *Languages {
	p := new(Languages)
	*p = x
	return p
}

func (x Languages) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Languages) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_sandbox_proto_enumTypes[0].Descriptor()
}

func (Languages) Type() protoreflect.EnumType {
	return &file_protos_sandbox_proto_enumTypes[0]
}

func (x Languages) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Languages.Descriptor instead.
func (Languages) EnumDescriptor() ([]byte, []int) {
	return file_protos_sandbox_proto_rawDescGZIP(), []int{0}
}

// Details and the code itself
type RunCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Language Languages `protobuf:"varint,1,opt,name=language,proto3,enum=Languages" json:"language,omitempty"`
	Code     string    `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *RunCodeRequest) Reset() {
	*x = RunCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_sandbox_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCodeRequest) ProtoMessage() {}

func (x *RunCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_sandbox_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCodeRequest.ProtoReflect.Descriptor instead.
func (*RunCodeRequest) Descriptor() ([]byte, []int) {
	return file_protos_sandbox_proto_rawDescGZIP(), []int{0}
}

func (x *RunCodeRequest) GetLanguage() Languages {
	if x != nil {
		return x.Language
	}
	return Languages_JAVASCRIPT
}

func (x *RunCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// Result of code execution
type RunCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *RunCodeResponse) Reset() {
	*x = RunCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_sandbox_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCodeResponse) ProtoMessage() {}

func (x *RunCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_sandbox_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCodeResponse.ProtoReflect.Descriptor instead.
func (*RunCodeResponse) Descriptor() ([]byte, []int) {
	return file_protos_sandbox_proto_rawDescGZIP(), []int{1}
}

func (x *RunCodeResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_protos_sandbox_proto protoreflect.FileDescriptor

var file_protos_sandbox_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4c, 0x0a, 0x0e, 0x52, 0x75, 0x6e, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67,
	0x75, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x4c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x22, 0x29, 0x0a, 0x0f, 0x52, 0x75, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2a,
	0x37, 0x0a, 0x09, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x0a,
	0x4a, 0x41, 0x56, 0x41, 0x53, 0x43, 0x52, 0x49, 0x50, 0x54, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a,
	0x54, 0x59, 0x50, 0x45, 0x53, 0x43, 0x52, 0x49, 0x50, 0x54, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06,
	0x47, 0x4f, 0x4c, 0x41, 0x4e, 0x47, 0x10, 0x02, 0x32, 0x37, 0x0a, 0x07, 0x53, 0x61, 0x6e, 0x64,
	0x62, 0x6f, 0x78, 0x12, 0x2c, 0x0a, 0x07, 0x52, 0x75, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0f,
	0x2e, 0x52, 0x75, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x10, 0x2e, 0x52, 0x75, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_sandbox_proto_rawDescOnce sync.Once
	file_protos_sandbox_proto_rawDescData = file_protos_sandbox_proto_rawDesc
)

func file_protos_sandbox_proto_rawDescGZIP() []byte {
	file_protos_sandbox_proto_rawDescOnce.Do(func() {
		file_protos_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_sandbox_proto_rawDescData)
	})
	return file_protos_sandbox_proto_rawDescData
}

var file_protos_sandbox_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_sandbox_proto_goTypes = []interface{}{
	(Languages)(0),          // 0: Languages
	(*RunCodeRequest)(nil),  // 1: RunCodeRequest
	(*RunCodeResponse)(nil), // 2: RunCodeResponse
}
var file_protos_sandbox_proto_depIdxs = []int32{
	0, // 0: RunCodeRequest.language:type_name -> Languages
	1, // 1: Sandbox.RunCode:input_type -> RunCodeRequest
	2, // 2: Sandbox.RunCode:output_type -> RunCodeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_sandbox_proto_init() }
func file_protos_sandbox_proto_init() {
	if File_protos_sandbox_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_sandbox_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_sandbox_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_sandbox_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_sandbox_proto_goTypes,
		DependencyIndexes: file_protos_sandbox_proto_depIdxs,
		EnumInfos:         file_protos_sandbox_proto_enumTypes,
		MessageInfos:      file_protos_sandbox_proto_msgTypes,
	}.Build()
	File_protos_sandbox_proto = out.File
	file_protos_sandbox_proto_rawDesc = nil
	file_protos_sandbox_proto_goTypes = nil
	file_protos_sandbox_proto_depIdxs = nil
}
